# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
