# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
