# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='description',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
