# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20170418_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
