# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
