# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20170418_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='polls.Category', verbose_name='Категория'),
        ),
    ]
