# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
