# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170422_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_code',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
