# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
    ]
