# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('img', models.CharField(db_index=True, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(db_index=True, max_length=1000)),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'ordering': ['created', 'updated'],
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Обявления',
            },
        ),
    ]
