# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.CharField(db_index=True, default=0, max_length=200),
        ),
    ]
