# Generated by Django 2.0.6 on 2018-06-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180621_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filt',
            old_name='category',
            new_name='cats',
        ),
    ]
