# Generated by Django 2.0.6 on 2018-06-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180622_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='filt',
        ),
    ]
