# Generated by Django 2.0.6 on 2018-06-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_color_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.PositiveIntegerField(verbose_name='Объём памяти')),
            ],
            options={
                'verbose_name': 'Память',
                'verbose_name_plural': 'Память',
                'ordering': ['val'],
            },
        ),
    ]
