# Generated by Django 2.0.6 on 2018-06-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20180622_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='verb',
            field=models.CharField(db_index=True, default=0, max_length=200),
            preserve_default=False,
        ),
    ]
