# Generated by Django 2.0.6 on 2018-06-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_unit_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.PositiveIntegerField(verbose_name='Объём')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram_sizes', to='shop.Unit', verbose_name='Единицы')),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
                'ordering': ['val'],
            },
        ),
    ]
