# Generated by Django 2.0.6 on 2018-06-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20180622_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Диагональ экрана')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagonal', to='shop.Unit', verbose_name='Диагональ экрана')),
            ],
            options={
                'verbose_name': 'Диагональ экрана',
                'verbose_name_plural': 'Диагонали экрана',
                'ordering': ['val'],
            },
        ),
        migrations.AlterField(
            model_name='ram',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram_sizes', to='shop.Unit', verbose_name='Объём оперативной памяти'),
        ),
    ]
