# Generated by Django 2.0.6 on 2018-06-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20180622_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='display',
            options={'ordering': ['name'], 'verbose_name': 'Тип дисплея', 'verbose_name_plural': 'Типы дисплея'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
    ]
