# Generated by Django 2.0.6 on 2018-06-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20180623_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diagonal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='diagonal', to='shop.Diagonal', verbose_name='Диагональ экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='display', to='shop.Display', verbose_name='Дисплей'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='shop.Material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='shop.Memory', verbose_name='Память'),
        ),
        migrations.AddField(
            model_name='product',
            name='proc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='proc', to='shop.Proc', verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='shop.Ram', verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='polls/static/shop/products/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
