# Generated by Django 2.0.6 on 2018-06-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20180623_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagonal',
            name='name',
            field=models.CharField(db_index=True, default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory',
            name='name',
            field=models.CharField(db_index=True, default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='name',
            field=models.CharField(db_index=True, default=0, max_length=200),
            preserve_default=False,
        ),
    ]
