# Generated by Django 2.0.6 on 2018-06-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20180623_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='refer_to',
            field=models.ManyToManyField(related_name='refer_to', to='shop.SubCat', verbose_name='Совместимость'),
        ),
    ]
