# Generated by Django 2.0.6 on 2018-07-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_product_refer_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(db_index=True, default=0, max_length=200),
        ),
    ]
