# Generated by Django 2.0.6 on 2018-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='img',
            field=models.ImageField(blank=True, upload_to='polls/static/shop/ads/', verbose_name='Изображение товара'),
        ),
    ]
